--JOINS INICIO

SELECT P.NOME_PESSOA,
       U.LOGIN USUARIO,
       PU.DSC_PERFIL_USUARIO
FROM PESSOA P
JOIN USUARIO U ON P.COD_PESSOA = U.COD_PESSOA
JOIN PERFIL_USUARIO PU ON U.COD_PERFIL_USUARIO = PU.COD_PERFIL_USUARIO
SELECT PES.NOME_PESSOA,
       D.NOME_DISCIPLINA,
       PRD.NUM_PERIODO
FROM DISCIPLINA D
JOIN PROFESSOR PROF ON D.COD_PROFESSOR = PROF.COD_PROFESSOR
JOIN PERIODO PRD ON D.COD_PERIODO = PRD.COD_PERIODO
JOIN PESSOA PES ON PROF.COD_PROFESSOR = PES.COD_PESSOA --JOINS FIM
 -- VIEWS INICIO

CREATE VIEW VW_DADOS_DISCIPLINA AS
SELECT PES.NOME_PESSOA PROFESSOR,
       D.NOME_DISCIPLINA DISCIPLINA,
       PRD.NUM_PERIODO PERÍODO
FROM DISCIPLINA D
JOIN PROFESSOR PROF ON D.COD_PROFESSOR = PROF.COD_PROFESSOR
JOIN PERIODO PRD ON D.COD_PERIODO = PRD.COD_PERIODO
JOIN PESSOA PES ON PROF.COD_PROFESSOR = PES.COD_PESSOA
CREATE VIEW VW_DADOS_USUARIO AS
SELECT P.NOME_PESSOA NOME,
       U.LOGIN USUARIO,
       PU.DSC_PERFIL_USUARIO PERFIL,
       P.EMAIL [E-MAIL]
FROM PESSOA P
JOIN USUARIO U ON P.COD_PESSOA = U.COD_PESSOA
JOIN PERFIL_USUARIO PU ON U.COD_PERFIL_USUARIO = PU.COD_PERFIL_USUARIO 
--VIEWS FIM

 --OPERAÇÕES LIKE , BETWEEN , IN INICIO

SELECT P.NOME_PESSOA
FROM USUARIO U
JOIN PERFIL_USUARIO PU ON U.COD_PERFIL_USUARIO = PU.COD_PERFIL_USUARIO
JOIN PESSOA P ON P.COD_PESSOA = U.COD_PESSOA
WHERE P.EMAIL LIKE '@hotmail.com%'

  SELECT D.NOME_DISCIPLINA,
         D.QTD_CARGA_HORARIA
  FROM DISCIPLINA D
  JOIN PERIODO P ON D.COD_PERIODO = P.COD_PERIODO
  JOIN PROFESSOR PROF ON D.COD_PROFESSOR = PROF.COD_PROFESSOR WHERE P.NUM_PERIODO BETWEEN 4 AND 6

  SELECT D.NOME_DISCIPLINA,
         H.NUM_HORARIO,
         DS.NOME_DIA_SEMANA
  FROM DISCIPLINA D
  JOIN HORARIO H ON D.COD_HORARIO = H.COD_HORARIO
  JOIN DIA_SEMANA DS ON DS.COD_DIA_SEMANA = H.COD_DIA_SEMANA WHERE DS.COD_DIA_SEMANA IN (
  SELECT DS2.COD_DIA_SEMANA
  FROM DIA_SEMANA DS2 WHERE DS.NOME_DIA_SEMANA IN('QUARTA-FEIRA',
                                                  'QUINTA-FEIRA')) 
												  
--OPERAÇÕES LIKE , BETWEEN E IN FIM
 --CONSULTAS união, interseção e diferença INICIO

  SELECT P.NOME_PESSOA
  FROM USUARIO U
  JOIN PERFIL_USUARIO PU ON U.COD_PERFIL_USUARIO = PU.COD_PERFIL_USUARIO
  JOIN PESSOA P ON P.COD_PESSOA = U.COD_PESSOA
UNION
SELECT P.NOME_PESSOA
FROM USUARIO U
JOIN PERFIL_USUARIO PU ON U.COD_PERFIL_USUARIO = PU.COD_PERFIL_USUARIO
JOIN PESSOA P ON P.COD_PESSOA = U.COD_PESSOA
WHERE P.EMAIL NOT LIKE '@hotmail.com%'

  SELECT P.NOME_PESSOA
  FROM USUARIO U
  JOIN PERFIL_USUARIO PU ON U.COD_PERFIL_USUARIO = PU.COD_PERFIL_USUARIO
  JOIN PESSOA P ON P.COD_PESSOA = U.COD_PESSOA WHERE PU.COD_PERFIL_USUARIO NOT IN
    (SELECT PU2.COD_PERFIL_USUARIO
     FROM PERFIL_USUARIO PU2
     WHERE PU2.DSC_PERFIL_USUARIO = 'Aluno')

  SELECT P.NOME_PESSOA
  FROM PESSOA P
  JOIN PROFESSOR PROF ON P.COD_PESSOA = PROF.COD_PESSOA
  JOIN DISCIPLINA D ON D.COD_PROFESSOR = PROF.COD_PROFESSOR 
  INTERSECT
  SELECT P.NOME_PESSOA
  FROM DISCIPLINA D
  JOIN PROFESSOR PROF ON PROF.COD_PROFESSOR = D.COD_PROFESSOR
  JOIN PESSOA P ON PROF.COD_PESSOA = P.COD_PESSOA WHERE D.COD_PROFESSOR IS NULL 
  --CONSULTAS união, interseção e diferença FIM


 --CONSULTA AGREGRADAS (SUM, COUNT, MAX, MIN, AVG) 2 COM GROUP BY e HAVING. INICIO
 --CONSULTA AGREGRADAS (SUM, COUNT, MAX, MIN, AVG) 2 COM GROUP BY e HAVING. FIM
