/* TI_BD_FISICO: */

CREATE TABLE USUARIO (
    COD_USUARIO INTEGER IDENTITY(1,1) PRIMARY KEY,
    [LOGIN] NVARCHAR(20) NOT NULL ,
    SENHA NVARCHAR(20) NOT NULL,
    COD_PERFIL_USUARIO INTEGER NOT NULL,
    COD_PESSOA INTEGER NOT NULL
); 

CREATE TABLE PERFIL_USUARIO (
    COD_PERFIL_USUARIO INTEGER IDENTITY(1,1) PRIMARY KEY,
    DSC_PERFIL_USUARIO NVARCHAR(20)  NOT NULL
);

CREATE TABLE PROFESSOR (
    COD_PROFESSOR INTEGER IDENTITY(1,1) PRIMARY KEY,
    COD_PESSOA INTEGER NOT NULL
);

CREATE TABLE PESSOA (
    COD_PESSOA INTEGER IDENTITY(1,1) PRIMARY KEY,
    COD_CPF NVARCHAR(11) NOT NULL,
    NOME_PESSOA NVARCHAR(100) NOT NULL,
    EMAIL NVARCHAR(100) NOT NULL
);

CREATE TABLE ALUNO (
    COD_ALUNO INTEGER IDENTITY(1,1) PRIMARY KEY,
    COD_PESSOA INTEGER NOT NULL
);

CREATE TABLE DISCIPLINA (
    COD_DISCIPLINA INTEGER IDENTITY(1,1) PRIMARY KEY,
    NOME_DISCIPLINA NVARCHAR(30),
    QTD_CARGA_HORARIA INTEGER,
    COD_HORARIO INTEGER,
    COD_PROFESSOR INTEGER,
    COD_PERIODO INTEGER
);

CREATE TABLE HORARIO (
    COD_HORARIO INTEGER IDENTITY(1,1) PRIMARY KEY,
    NUM_HORARIO NVARCHAR(10),
    COD_DIA_SEMANA INTEGER
);

CREATE TABLE DIA_SEMANA (
    COD_DIA_SEMANA INTEGER IDENTITY(1,1) PRIMARY KEY,
    NOME_DIA_SEMANA NVARCHAR(20)
);

CREATE TABLE PERIODO (
    COD_PERIODO INTEGER IDENTITY(1,1) PRIMARY KEY,
    NUM_PERIODO INTEGER
);

CREATE TABLE AULA (
    COD_ALUNO INTEGER,
    COD_DISCIPLINA INTEGER
);
 
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_1
    FOREIGN KEY (COD_PERFIL_USUARIO)
    REFERENCES PERFIL_USUARIO (COD_PERFIL_USUARIO)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_2
    FOREIGN KEY (COD_PESSOA)
    REFERENCES PESSOA (COD_PESSOA)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE DISCIPLINA ADD CONSTRAINT FK_DISCIPLINA_1
    FOREIGN KEY (COD_HORARIO)
    REFERENCES HORARIO (COD_HORARIO)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE DISCIPLINA ADD CONSTRAINT FK_DISCIPLINA_2
    FOREIGN KEY (COD_PROFESSOR)
    REFERENCES PROFESSOR (COD_PROFESSOR)
    ON DELETE SET NULL ON UPDATE CASCADE;
 
ALTER TABLE DISCIPLINA ADD CONSTRAINT FK_DISCIPLINA_3
    FOREIGN KEY (COD_PERIODO)
    REFERENCES PERIODO (COD_PERIODO)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE HORARIO ADD CONSTRAINT FK_HORARIO_1
    FOREIGN KEY (COD_DIA_SEMANA)
    REFERENCES DIA_SEMANA (COD_DIA_SEMANA)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE PROFESSOR ADD CONSTRAINT FK_PROFESSOR_1
    FOREIGN KEY (COD_PESSOA)
    REFERENCES PESSOA (COD_PESSOA)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE ALUNO ADD CONSTRAINT FK_ALUNO_1
    FOREIGN KEY (COD_PESSOA)
    REFERENCES PESSOA (COD_PESSOA)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE AULA ADD CONSTRAINT FK_AULA_0
    FOREIGN KEY (COD_ALUNO)
    REFERENCES ALUNO (COD_ALUNO)
    ON DELETE SET NULL ON UPDATE CASCADE;
 
ALTER TABLE AULA ADD CONSTRAINT FK_AULA_1
    FOREIGN KEY (COD_DISCIPLINA)
    REFERENCES DISCIPLINA (COD_DISCIPLINA)
    ON DELETE SET NULL --ON UPDATE CASCADE;