DELIMITER $$
CREATE  PROCEDURE SPDELETA_PERFIL( pkPerfil   INTEGER)
BEGIN
    UPDATE  USUARIO
    SET     COD_PERFIL_USUARIO = NULL
    WHERE   COD_PERFIL_USUARIO = pkPerfil;
	DELETE FROM PERFIL_USUARIO 
WHERE
    COD_PERFIL_USUARIO = pkPerfil;
END $$
DELIMITER ;