CREATE  PROC [dbo].[SPDELETA_PERFIL] @pkPerfil AS INTEGER
AS
    UPDATE  USUARIO
    SET     COD_PERFIL_USUARIO = NULL
    WHERE   COD_PERFIL_USUARIO = @pkPerfil;
    DELETE  FROM PERFIL_USUARIO
    WHERE   COD_PERFIL_USUARIO = @pkPerfil;